common:
  management:
    metrics:
      tags:
        application: ${spring.cloud.task.name:unknown}-${spring.cloud.task.executionid:unknown}
        service: "task-application"

local:

kubernetes:

cloudfoundry:
