common:
  management:
    metrics:
      tags:
        # Common Spring Cloud Data Flow stream app tags.
        stream.name: ${spring.cloud.dataflow.stream.name:unknown}
        application.name: ${vcap.application.application_name:${spring.cloud.dataflow.stream.app.label:unknown}}
        application.type: ${spring.cloud.dataflow.stream.app.type:unknown}
        instance.index: ${vcap.application.instance_index:${spring.cloud.stream.instanceIndex:0}}
        application.guid: ${spring.cloud.application.guid:unknown}

        # Tags required to use the Wavefront Spring Boot tile.
        application: ${spring.cloud.dataflow.stream.name:unknown}-${spring.cloud.dataflow.stream.app.label:unknown}-${spring.cloud.dataflow.stream.app.type:unknown}
    endpoints:
      web:
        exposure:
          include: health,info,bindings

  # Properties required for Wavefront Tracing.
  wavefront.application.name: ${spring.cloud.dataflow.stream.name:unknown}
  wavefront.application.service: ${spring.cloud.dataflow.stream.app.label:unknown}-${spring.cloud.dataflow.stream.app.type:unknown}-${vcap.application.instance_index:${spring.cloud.stream.instanceIndex:0}}

local:

kubernetes:

cloudfoundry:
  management:
    metrics:
      tags:
        # Tags applicable only for the CF environment.
        organization.name: ${vcap.application.org_name:default}
        space.id: ${vcap.application.space_id:unknown}
        space.name: ${vcap.application.space_name:unknown}
        application.id: ${vcap.application.application_id:unknown}
        application.version: ${vcap.application.application_version:unknown}
