#@ load("external.star", "name")
#@ load("external.star", "username")
#@ load("external.star", "password")
#@ load("@ytt:base64", "base64")

apiVersion: v1
kind: Secret
metadata:
  name: #@ name()
  labels:
    app: #@ name()
data:
  external-user: #@ base64.encode(username())
  external-password: #@ base64.encode(password())
