apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: web
  repo: https://charts.getporter.dev
  releaseName: porter-server
  valuesFile: server.yaml
- name: web
  repo: https://charts.getporter.dev
  releaseName: porter-auth
  valuesFile: auth.yaml

configMapGenerator:
- name: porter-server-env
  env: .server.env
generatorOptions:
  disableNameSuffixHash: true

patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: porter-server-web
  spec:
    template:
      spec:
        containers:
        - name: web
          envFrom:
          - configMapRef: 
              name: porter-server-env
          volumeMounts:
          - mountPath: /app/ssh
            name: ssh-keys
        volumes:
        - name: ssh-keys
          hostPath:
            path: /local-user/.ssh
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: porter-auth-web
  spec:
    template:
      spec:
        containers:
          - name: web
            envFrom:
              - configMapRef:
                  name: porter-server-env
            volumeMounts:
              - mountPath: /app/ssh
                name: ssh-keys
        volumes:
          - name: ssh-keys
            hostPath:
              path: /local-user/.ssh
