apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: postgresql
spec:
  type: NodePort
  ports:
    - port: 5432
      name: postgresql
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgresql
