apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-errors
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-errors
    spec:
      containers:
      - name: nginx-errors
        image: gcr.io/porter-dev-273614/error-backend:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 20m
            memory: 40Mi
          requests:
            cpu: 10m
            memory: 20Mi      