--- # About installing nginx and notifiying handler for restart
- hosts: ubuntu
  remote_user: ansible
  become: yes
  tasks:
  - name: Install nginx
    apt:
      name: nginx
      state: latest
    notify: restart nginx
  handlers:
  - name: restart nginx
    service:
      name: nginx
      enabled: yes
      state: restarted
