---
- hosts: all
  become: yes
  gather_facts: no
  tasks:
  - name: "Copy python script"
    copy:
      src: simple_python_script.py
      dest: /home/ansible/simple_python_script.py
  - name: "Add MYVAR to the bash profile"
    lineinfile:
      path: /home/ansible/.bash_profile
      line: "export MYVAR={{inventory_hostname}}"
  - name: "Create the cronjob to run the script"
    cron:
      name: "Run simple_python_script  every minute"
      minute: "*/1"
      job: "/bin/sh -c '. ~/.bash_profile; /usr/bin/python /home/ansible/simple_python_script.py'"
      disabled: "no"
    become_user: ansible
