---
- hosts: centos
  gather_facts: no
  vars:
    - USER: r3ap3rpy
    - PASS: Start!123
  tasks:
  - name: Create the file or config
    file:
     path: /tmp/secret.conf
     owner: ansible
     group: ansible
     state: touch
  - name: Fill the sensitive information
    lineinfile:
      path: /tmp/secret.conf
      line: "{{USER}}:{{PASS}}"
      state: present
