---
- hosts: centos
  become: yes
  gather_facts: yes
  tasks:
  - name: "Get the local facts custom_ini"
    debug:
      msg: "Coming from local custom_ini {{ansible_local.custom_ini}}"
  - name: "Get the local facts test_fact"
    debug:
      msg: "Coming from local test_fact {{ansible_local.test_fact}}"
