---
- hosts: cento
  become: yes
  tasks:
  - name: "Install epel release"
    yum:
      name: epel-release
      state: latest
  - name: "Install nginx"
    yum:
      name: nginx
      state: latest
    notify:
      - restart and enable
  handlers:
  - name: restart and enable
    service:
      name: nginx
      state: restarted
      enabled: yes
